[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sbmlmath"
version = "0.0.3"
authors = [
    {name = "Daniel Weindl", email = "sci@danielweindl.de"},
]
description = "SBML Math <-> SymPy"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD-3-Clause"}
dependencies = [
    "python-libsbml",
    "sympy",
    "pint",
    "lxml>=4.6.4",
]

[project.optional-dependencies]
test = ["pytest>=7", "pre-commit>=3"]

[tool.black]
line-length = 80
