name: Deploy
on:
  release:
    types:
      - published

jobs:
  pypi:
    name: Deploy PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/sbmlmath
    permissions:
      id-token: write

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 20

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
        python -m build -s

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
